resources:
  - ../07-services

components:
  - ../../components/pods

patches:
  # TODO(logiraptor): Jsonnet sets JAEGER_REPORTER_MAX_QUEUE_SIZE on the querier
  - target:
      name: mimir-querier
      kind: Deployment
    patch: |-
      - op: remove
        path: /spec/template/spec/containers/0/env

  # TODO(logiraptor): Jsonnet sets POD_IP on the alertmanager
  - target:
      name: mimir-alertmanager
      kind: StatefulSet
    patch: |-
      - op: remove
        path: /spec/template/spec/containers/0/env
