name: compare-helm-with-jsonnet

on:
  push:
    branches:
      - logiraptor/use-k8s-diff

jobs:
  compare-manifests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: helm/kind-action@v1.2.0
    - uses: frenck/action-setup-yq@a2ad11c46c5d7ba576861216963c9365b53f35bc
    - run: make check-helm-jsonnet-diff
      shell: bash
